SELECT * FROM TB_POST tb ;
SELECT * FROM TB_USER tu ;

SELECT tp.*, tu.USER_NAME 
FROM TB_POST tp , TB_USER tu 
WHERE tp.USER_UID = tu.USER_UID 
;

SELECT tp.*, tu.USER_NAME FROM TB_POST tp , TB_USER tu WHERE tp.USER_UID = tu.USER_UID AND tp.POST_UID = 3;