SELECT * FROM TB_POST tb ;
SELECT * FROM TB_USER tu ;
SELECT * FROM TB_COMMENT tc ;

SELECT tp.*, tu.USER_NAME, tc.comments_count
FROM TB_POST tp JOIN TB_USER tu
ON tp.USER_UID = tu.USER_UID 
LEFT OUTER JOIN (SELECT tp.POST_UID, COUNT(tc.POST_UID) AS comments_count FROM TB_POST tp LEFT OUTER JOIN TB_COMMENT tc ON tp.POST_UID = tc.POST_UID GROUP BY tp.POST_UID) tc
ON tp.POST_UID = tc.POST_UID 
ORDER BY tp.POST_UID DESC 
;

SELECT tc.COMMENT_UID , tc.POST_UID  
FROM TB_POST tp LEFT OUTER JOIN TB_COMMENT tc 
ON tp.POST_UID = tc.POST_UID 
;

SELECT tp.POST_UID, COUNT(tc.POST_UID) AS comments_count FROM TB_POST tp LEFT OUTER JOIN TB_COMMENT tc ON tp.POST_UID = tc.POST_UID GROUP BY tp.POST_UID;

SELECT tp.*, tu.USER_NAME FROM TB_POST tp , TB_USER tu WHERE tp.USER_UID = tu.USER_UID AND tp.POST_UID = 3;
